# language: python
# python: 
#   - "3.8"

#   branches:
#     - master
#     - dev
#   services:
#     - docker
#   before_script: pip install docker-compose

#   script: 
#     - docker-compose run app sh -c "python manage.py test && flake8"

{
  "os": ["linux", "windows"],
  "language": "python",
  "dist": ["xenial", "server-2016"],
  "python": ["3.6","3.8"],
  "branches": ["master", "dev"],
  "services": "docker",
  "before_script": "pip install docker-compose",
  "script": "docker-compose run app sh -c 'python manage.py test && flake8'"
}