language: python
python: 
  - "3.6"

  services:
    - docker
  env:
    - DOCKER_COMPOSE_VERSION=1.27.3

  before_script: pip install docker-compose

  script: 
    - docker-compose run app sh -c "python manage.py test && flake8"